#!/bin/sh
# $Id$

clear
echo "Available DamnSmallBSD Releases"
echo "==============================="
echo ""
echo "d - HEAD"
echo ""
echo ""
read -p "Enter Choice: " CHOICE

if [ "${CHOICE}" = "d" ] ; then
	svn checkout svn://devnulled.ath.cx/damnsmallbsd/trunk/src dsbsd-head
fi
