#!/bin/sh
# Copyright 2007-2009 Dylan Cochran
# All rights reserved
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


# $Id$

svn up 2>&1 >/dev/null

END="$(svnversion | sed s_M__g)"
BEGIN="$(svn log -l 1 --xml | awk '/<logentry/, />/' | grep revision | cut -d \" -f 2)"
ORIGPATH="$(pwd)"
MAINPATH="$(cd ../../../../ && pwd)"
NUMBER="$((${END} - ${BEGIN}))"
TARGETPATH="$(echo ${ORIGPATH} | sed "s_${MAINPATH}__g")"
cd "${MAINPATH}"
svn up 2>&1 >/dev/null

if [ "${NUMBER}" != "0" ] ; then
	LOGMESSAGE="$(echo "Merge /trunk/src r${END} to ${TARGETPATH}"; echo ""; svn log -l ${NUMBER} --xml | mergelog)"
	cd "${ORIGPATH}"
	svn merge -r ${BEGIN}:${END} https://evoke.googlecode.com/svn/trunk/src .
	svn merge -r ${BEGIN}:${END} https://evoke.googlecode.com/svn/wiki doc
	svn commit -m "${LOGMESSAGE}"
fi
