#!/bin/sh
# Copyright 2007-2009 Dylan Cochran
# All rights reserved
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


# $Id$

replace_copyright() {
	sed -i .bak "\/Copyright/ s/${OLDDATE}/${NEWDATE}/g" ${1}
	rm ${1}.bak
}
copyright_loop () {
	if [ "${1}" = "" ] ; then
		exit 3
	fi
	OLDDATE=${1}
	shift

	if [ "${1}" = "" ] ; then
		exit 3
	fi
	NEWDATE=${1}
	shift

	while [ "${1}" != "" ]
	do
		local STAT_DEV="$(stat -f %d ${1})"
		local STAT_TYPE="$(stat -f %HT ${1})"
		case "${STAT_TYPE}" in
			Directory)
				for entry in $(ls -a "${1}")
				do
					echo "${entry}"
					if [ "${entry}" != "." -a "${entry}" != ".." -a "${entry}" != ".svn" ] ; then
						copyright_loop "${OLDDATE}" "${NEWDATE}" "${1}/${entry}"
					fi
				done
			;;
			Regular*)
				replace_copyright "${1}"
			;;
		esac
		shift
	done
}

copyright_loop $@
