#!/bin/sh
# Copyright 2007-2009 Dylan Cochran
# All rights reserved
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# $Id$
OPWD=$(pwd)

clear
echo "Available Evoke Releases"
echo "==============================="
echo ""
echo "1 - Evoke 0.1R1"
echo "1 - DSBSD 0.1P1"
echo "d - HEAD"
echo ""
echo ""
read -p "Enter Choice: " CHOICE

case "${CHOICE}" in
	[1])
		echo -n "Fetching DamnSmallBSD"
		DEST=dsbsd-0.1P1
		svn checkout http://evoke.googlecode.com/svn/branches/releases/0.1P1/src ${DEST} 2>/dev/null >/dev/null
		TARGETS=$(cat ${DEST}/build.sh | grep TARGETS= | cut -d \" -f 2)
	;;
	[dD])
		echo -n "Fetching Evoke"
		DEST=evoke-head
		svn checkout http://evoke.googlecode.com/svn/trunk/src ${DEST} 2>/dev/null >/dev/null
		TARGETS=$(cat ${DEST}/build.sh | grep TARGETS= | cut -d \" -f 2)
	;;
	*)
		echo -n "Fetching Evoke"
		DEST=evoke-0.1R1
		svn checkout "http://evoke.googlecode.com/svn/branches/releases/0.1/R1/src" "${DEST}" 2>/dev/null >/dev/null
		TARGETS=$(cat ${DEST}/build.sh | grep TARGETS= | cut -d \" -f 2)
	;;
esac
echo ""
